# intro of numpy

In [1]:
import numpy as np

In [2]:
arr1= np.array([[3,4,5,3,35],[1,3,5,42,3]], dtype= 'int32')

In [3]:
type(arr1)

numpy.ndarray

In [4]:
print(arr1.shape)

(2, 5)


In [5]:
arr1.dtype

dtype('int32')

# creation of numpy array

### 1.Conversion from other Python structures (e.g., lists, tuples)

In [6]:
marks = ( 3,5,2,25,673,476,2432,62,23)  #tuple
marks2 = [ 3,5,2,25,673,476,2432,62,23]  #list
arr2= np.array([[5,76,5,3,35],[1,3,5,42,3]])
type(marks)

tuple

In [7]:
type(marks2)

list

In [8]:
marks = np.array(marks)
marks2 = np.array(marks2)
type(marks)
type(marks2)

numpy.ndarray

In [9]:
marks[3]

25

### Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

In [10]:
sample_0 = np.zeros((2,6))
sample_0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
rng= np.arange(65)


In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [13]:
linear_space= np.linspace(1,50,5) 

In [14]:
linear_space

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [15]:
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
array = np.arange(80)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [17]:
reshaped_arr = array.reshape(4,20)
reshaped_arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79]])

In [18]:
x = np.array([[2,3,4,4,23],[2,35,24,2,3],[3,65,35,832,54],[73,5,24,754,3]])



In [19]:
x.sum(axis=0)

array([  80,  108,   87, 1592,   83])

In [20]:
x.T


array([[  2,   2,   3,  73],
       [  3,  35,  65,   5],
       [  4,  24,  35,  24],
       [  4,   2, 832, 754],
       [ 23,   3,  54,   3]])

In [21]:
x.nbytes


80

In [22]:
one_d_arr = np.array([2,4,36,3526,26,246,346,2,52,6])

In [23]:
one_d_arr.dtype

dtype('int32')

In [24]:
one_d_arr.argsort() #returens index of the elments as per the operation

array([0, 7, 1, 9, 4, 2, 8, 5, 6, 3], dtype=int64)

In [25]:
one_d_arr.argpartition(5)

array([1, 0, 7, 9, 4, 2, 5, 8, 6, 3], dtype=int64)

In [26]:
one_d_arr.argmax()

3

In [27]:
x

array([[  2,   3,   4,   4,  23],
       [  2,  35,  24,   2,   3],
       [  3,  65,  35, 832,  54],
       [ 73,   5,  24, 754,   3]])

In [28]:
x.argsort()

array([[0, 1, 2, 3, 4],
       [0, 3, 4, 2, 1],
       [0, 2, 4, 1, 3],
       [4, 1, 2, 0, 3]], dtype=int64)

In [29]:
x.argsort(axis =0)

array([[0, 0, 0, 1, 1],
       [1, 3, 1, 0, 3],
       [2, 1, 3, 3, 0],
       [3, 2, 2, 2, 2]], dtype=int64)

In [30]:
x_max = x.argmax(axis= 1)

In [31]:
for _ in x_max:
    print(x[_])


IndexError: index 4 is out of bounds for axis 0 with size 4

### slicing

In [32]:
arr2 = np.array([23,4,5,2,5,2,3,])

In [43]:
arr1 = arr2[1:5] # it will works as view so changees done in arr1 will be reflected to arr2 too, to avoid this we can do this
arr3 = arr2[1:5].copy()

In [36]:
arr1


array([5, 2, 5])

In [41]:
arr1[3]= 34


In [44]:
arr2

array([23,  4,  5,  2, 34,  2,  3])

In [45]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',